### ISSUE TITLE
broken arabic shaping in text frame

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#158]
see screenshot
![arbic](https://cloud.githubusercontent.com/assets/1632566/14704405/81ef1402-07c5-11e6-970c-e793f927a3a5.jpg)

test
[arabic.sla.gz](https://github.com/HOST-Oman/scribus/files/229591/arabic.sla.gz)
 file.

**Comment by khaledhosny** [comment]
Should be fixed now.

**Comment by Fahad-Alsaidi** [comment]
the problem is still happen. Noticed also when you type directly in text frame.
test file.
[arabic.sla.gz](https://github.com/HOST-Oman/scribus/files/229772/arabic.sla.gz)

**Comment by khaledhosny** [comment]
Looks like a different issue than the first file, investigating.

**Comment by khaledhosny** [comment]
Should be fixed now.

**Comment by Fahad-Alsaidi** [comment]
I confirm it is fixed. Thanks.
